[package]
name = "pofi-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

# Runtime
wasmtime = "27.0.0"
wat = "1.221.0"

# Monitoring
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

# Error handling
anyhow = "1.0.93"
