name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.81.0
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Lint
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.81.0
        with:
          components: clippy
          targets: wasm32-unknown-unknown
      - name: Set up Protoc
        uses: arduino/setup-protoc@v2
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run cargo check
        run: cargo check --all-targets --all-features

  test:
    name: Unit Tests
    needs: fmt
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.81.0
        with:
          targets: wasm32-unknown-unknown
      - name: Set up Protoc
        uses: arduino/setup-protoc@v2
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run tests
        run: cargo test --all-features

  modules:
    name: WebAssembly Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.81.0
        with:
          targets: wasm32-unknown-unknown
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-wasm-${{ hashFiles('**/Cargo.lock') }}
      - name: Build example modules
        run: |
          find modules -mindepth 1 -maxdepth 1 -type d | while read -r dir; do
            if [ -f "$dir/Cargo.toml" ]; then
              echo "Building $dir..."
              cd "$dir"
              
              # Get all features from Cargo.toml
              if [ -f "Cargo.toml" ]; then
                FEATURES=$(cargo metadata --no-deps --format-version 1 | \
                  jq -r '.packages[0].features | keys[]' 2>/dev/null || echo "")
              else
                FEATURES=""
              fi
              
              # If no features, build default
              if [ -z "$FEATURES" ]; then
                RUSTFLAGS="-C target-feature=+multivalue" cargo build --target wasm32-unknown-unknown --release
              else
                # Build each feature
                for feature in $FEATURES; do
                  echo "Building with feature: $feature"
                  RUSTFLAGS="-C target-feature=+multivalue" cargo build --target wasm32-unknown-unknown --release --features "$feature"
                done
              fi
              
              cd - > /dev/null
            fi
          done
